### PR TITLE
Expand nunjucks dep to include 3.0.0

### PR DESCRIPTION
**Pull request by jgerigmeyer**

### CODE REVIEW

**Comment by pierreant-p** [comment]
Thanks for the PR !
I pushed 0.0.7 to npm with your changes https://www.npmjs.com/package/jinja-loader

**Comment by jgerigmeyer** [comment]
👍

**Comment by pierreant-p** [comment]
Can I ask in which project you use `jinja-loader` ?

**Comment by jgerigmeyer** [comment]
Honestly I use it in all of my client web apps where I use webpack. Unfortunately all of them are private repos for now...

**Comment by pierreant-p** [comment]
Awesome !
Thanks for the PR and let me know if there's something we can improve.
(We use it mainly on sketchfab.com)

**Comment by jgerigmeyer** [comment]
Oh, actually, the repos are private but some of the projects have launched. I used jinja-loader in these various projects:
- https://coachhub.resilienceboost.com/
- https://www.quarqnet.com/ (described at http://www.quarq.com/pages/quarq-qollector)
- https://www.quarqrace.com/

**Comment by pierreant-p** [comment]
Thanks for the links!
(I think there are some js issues on the quar<xyz>.com pages :(

**Comment by jgerigmeyer** [comment]
Yeah, I'm not responsible for top-level quarq.com...

**Comment by pierreant-p** [comment]
:)

**Pull request merged**
