### PR TITLE
Expand nunjucks dep to include ^2.0.0.

### PR DESCRIPTION
**Pull request by jgerigmeyer**

### CODE REVIEW

**Comment by pierreant-p** [comment]
Hey, did you try? Everything works fine?

**Comment by jgerigmeyer** [comment]
Yes, I've been using it for a few days without trouble. There aren't significant changes to the API in nunjucks 2.0.0 (see https://github.com/mozilla/nunjucks/blob/master/CHANGELOG.md).

**Comment by pierreant-p** [comment]
ok thanks!

**Comment by jgerigmeyer** [comment]
:+1: Might be worth a version bump to 0.0.3 (and republishing to npm)?

**Comment by pierreant-p** [comment]
Sure. Done!

**Pull request merged**
