### PR TITLE
enable additional environment config

### PR DESCRIPTION
**Pull request by brad**
Hi, I needed to make changes to the environment to support the markdown tag. Here's my take on how it can be generalized to make general environment configuration changes before compiling. I'm not a node expert, but this worked for me! Please let me know if you see any issues.

### CODE REVIEW

**Comment by pierreant-p** [comment]
Thank you for the pull request. Out of curiosity, what is your use-case?

**Comment by brad** [comment]
Webpack was throwing errors about markdown tags in my templates and this fixed it.

**Comment by pierreant-p** [comment]
ok I will try if this PR doesn't break our usage of the package and merge it if it's ok

**Comment by pierreant-p** [comment]
@brad thx for the PR, I pushed an update on npm (0.0.4). Let me know how it goes!

**Comment by brad** [comment]
Thanks, I'll give it a try!

**Comment by pierreant-p** [comment]
Update: this change lead to a huge build performance issue for us (we have a large codebase with 2000+ plus modules). I'm pretty sure that the "new Environment()" is too expensive and slows everything down. I'll have a look, but I might have to revert the change ...

**Comment by pierreant-p** [comment]
@brad fixed in 0.0.6

**Pull request merged**
